export const users = [],
  borrowBooks = [],
  books = [
    { "title": "The Adventures of Huckleberry Finn", "availableCopies": 2 },
    { "title": "Moby Dick", "availableCopies": 3 },
    { "title": "Pride and Prejudice", "availableCopies": 4 },
    { "title": "The Great Gatsby", "availableCopies": 5 },
    { "title": "To Kill a Mockingbird", "availableCopies": 3 },
    { "title": "1984", "availableCopies": 6 },
    { "title": "The Catcher in the Rye", "availableCopies": 2 },
    { "title": "War and Peace", "availableCopies": 1 },
    { "title": "The Odyssey", "availableCopies": 4 },
    { "title": "Ulysses", "availableCopies": 3 },
    { "title": "Brave New World", "availableCopies": 5 },
    { "title": "Frankenstein", "availableCopies": 2 },
    { "title": "The Lord of the Rings", "availableCopies": 7 },
    { "title": "Crime and Punishment", "availableCopies": 4 },
    { "title": "The Picture of Dorian Gray", "availableCopies": 3 },
    { "title": "Wuthering Heights", "availableCopies": 2 },
    { "title": "Jane Eyre", "availableCopies": 5 },
    { "title": "Dracula", "availableCopies": 4 },
    { "title": "Anna Karenina", "availableCopies": 3 },
    { "title": "The Grapes of Wrath", "availableCopies": 2 },
    { "title": "The Hobbit", "availableCopies": 6 },
    { "title": "The Divine Comedy", "availableCopies": 2 },
    { "title": "Don Quixote", "availableCopies": 3 },
    { "title": "The Brothers Karamazov", "availableCopies": 4 },
    { "title": "One Hundred Years of Solitude", "availableCopies": 2 },
    { "title": "The Stranger", "availableCopies": 5 },
    { "title": "The Count of Monte Cristo", "availableCopies": 3 },
    { "title": "Les Misérables", "availableCopies": 7 },
    { "title": "The Iliad", "availableCopies": 4 },
    { "title": "Fahrenheit 451", "availableCopies": 3 },
    { "title": "The Scarlet Letter", "availableCopies": 2 },
    { "title": "The Sun Also Rises", "availableCopies": 5 },
    { "title": "Catch-22", "availableCopies": 4 },
    { "title": "The Road", "availableCopies": 3 },
    { "title": "The Handmaid's Tale", "availableCopies": 2 },
    { "title": "The Bell Jar", "availableCopies": 3 },
    { "title": "The Old Man and the Sea", "availableCopies": 2 },
    { "title": "The Trial", "availableCopies": 4 },
    { "title": "Heart of Darkness", "availableCopies": 3 },
    { "title": "A Tale of Two Cities", "availableCopies": 5 },
    { "title": "The Jungle", "availableCopies": 2 },
    { "title": "The Catcher in the Rye", "availableCopies": 4 },
    { "title": "Lolita", "availableCopies": 2 },
    { "title": "The Bell Jar", "availableCopies": 3 },
    { "title": "The Secret Garden", "availableCopies": 6 },
    { "title": "Little Women", "availableCopies": 4 },
    { "title": "Alice's Adventures in Wonderland", "availableCopies": 5 },
    { "title": "Through the Looking-Glass", "availableCopies": 3 },
    { "title": "The Wind in the Willows", "availableCopies": 2 },
    { "title": "The Call of the Wild", "availableCopies": 3 },
    { "title": "The Jungle Book", "availableCopies": 4 },
    { "title": "Dr. Jekyll and Mr. Hyde", "availableCopies": 5 },
    { "title": "Treasure Island", "availableCopies": 4 },
    { "title": "The Adventures of Sherlock Holmes", "availableCopies": 3 },
    { "title": "The Memoirs of Sherlock Holmes", "availableCopies": 4 },
    { "title": "The Hound of the Baskervilles", "availableCopies": 2 },
    { "title": "The Sign of the Four", "availableCopies": 3 },
    { "title": "A Study in Scarlet", "availableCopies": 5 },
    { "title": "The Three Musketeers", "availableCopies": 6 },
    { "title": "Around the World in Eighty Days", "availableCopies": 4 },
    { "title": "Journey to the Center of the Earth", "availableCopies": 3 },
    { "title": "20,000 Leagues Under the Sea", "availableCopies": 2 },
    { "title": "The Invisible Man", "availableCopies": 4 },
    { "title": "The War of the Worlds", "availableCopies": 3 },
    { "title": "The Time Machine", "availableCopies": 2 },
    { "title": "The Island of Doctor Moreau", "availableCopies": 5 },
    { "title": "The Man Who Would Be King", "availableCopies": 3 },
    { "title": "The Secret Agent", "availableCopies": 4 },
    { "title": "The Shape of Things to Come", "availableCopies": 2 },
    { "title": "The Sea-Wolf", "availableCopies": 3 },
    { "title": "The Call of Cthulhu", "availableCopies": 2 },
    { "title": "The Shadow over Innsmouth", "availableCopies": 4 },
    { "title": "At the Mountains of Madness", "availableCopies": 3 },
    { "title": "The Dunwich Horror", "availableCopies": 2 },
    { "title": "The Colour Out of Space", "availableCopies": 5 },
    { "title": "The Whisperer in Darkness", "availableCopies": 3 },
    { "title": "The Haunter of the Dark", "availableCopies": 2 },
    { "title": "The Dunwich Horror", "availableCopies": 4 },
    { "title": "The Shadow over Innsmouth", "availableCopies": 3 },
    { "title": "The Call of Cthulhu", "availableCopies": 5 },
    { "title": "The Horror at Red Hook", "availableCopies": 2 },
    { "title": "The Haunter of the Dark", "availableCopies": 3 },
    { "title": "The Dunwich Horror", "availableCopies": 4 },
    { "title": "The Whisperer in Darkness", "availableCopies": 2 },
    { "title": "The Colour Out of Space", "availableCopies": 5 },
    { "title": "The Case of Charles Dexter Ward", "availableCopies": 4 },
    { "title": "The Curse of Yig", "availableCopies": 3 },
    { "title": "The Shadow Out of Time", "availableCopies": 2 },
    { "title": "The Call of Cthulhu", "availableCopies": 4 },
    { "title": "The Dunwich Horror", "availableCopies": 3 },
    { "title": "The Whisperer in Darkness", "availableCopies": 5 },
    { "title": "The Haunter of the Dark", "availableCopies": 4 },
    { "title": "The Colour Out of Space", "availableCopies": 3 },
    { "title": "The Shadow Over Innsmouth", "availableCopies": 2 },
    { "title": "The Call of Cthulhu", "availableCopies": 5 },
    { "title": "The Whisperer in Darkness", "availableCopies": 4 },
    { "title": "The Dunwich Horror", "availableCopies": 3 },
    { "title": "The Horror at Red Hook", "availableCopies": 2 }
  ]
  ;
